apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master # Matches the label on your Jenkins pod
  ports:
    - protocol: TCP
      port: 8080 # The port inside the service
      targetPort: 8080 # The port on the Jenkins container
      nodePort: 32000 # The static port exposed on every node
