apiVersion: v1
kind: Namespace
metadata:
  name: dev-ide

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
  namespace: dev-ide
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      # This 'nodeSelector' forces the pod to run ONLY on gti15-cpu.
      nodeSelector:
        kubernetes.io/hostname: gti15-cpu
      containers:
      - name: code-server
        image: codercom/code-server:latest
        ports:
        - containerPort: 8080
        env:
        # --- IMPORTANT: Set your login password below! ---
        - name: PASSWORD
          value: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
  namespace: dev-ide
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080