apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: my-ray-cluster
spec:
  rayVersion: "2.48.0" # Specify your desired Ray version
  headGroupSpec:
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray:2.48.0-py311-aarch64
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
  workerGroupSpecs:
    - groupName: small-group  # Add a unique name for this worker group
      replicas: 1
      minReplicas: 1
      maxReplicas: 5
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray:latest-aarch64
              resources:
                limits:
                  cpu: "1"
                  memory: "2Gi"
